import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'de' | 'fr' | 'es' | 'ar';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar / Common
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.investment": "Investment",
    "nav.custom": "Custom",
    "nav.consultation": "Consultation",
    "nav.locations": "Locations",
    "nav.switch": "Language",
    
    // Home Hero
    "hero.tagline": "The Standard of Wealth",
    "hero.title1": "Own Gold.",
    "hero.title2": "Wear Power.",
    "hero.desc": "Curating the world's most exquisite 18K, 21K, 22K, and 24K gold collections. From artisanal fashion jewelry to high-yield gold bar investments.",
    "hero.btn.jewelry": "Shop Jewelry",
    "hero.btn.invest": "Invest in Gold",
    "hero.explore": "Explore AU718",
    
    // Featured Sections
    "feat.tagline": "Our Curated World",
    "feat.title": "Featured Collections",
    "feat.view_all": "View All Jewelry",
    "feat.view_col": "View Collection",
    
    // Locations page
    "loc.tagline": "Our Presence",
    "loc.title": "Store Locations",
    "loc.desc": "Experience the weight of pure gold in person. Visit our premium showrooms for a private viewing and consultation.",
    "loc.address_label": "Address",
    "loc.working_hours_title": "Opening Hours",
    "loc.working_hours_details": "Mon - Sat: 9:00 AM - 6:00 PM",
    "loc.direct_contact": "Direct Contact",
    "loc.get_directions": "Get Directions",
    "loc.cant_visit_title": "Can't Visit Us In Store?",
    "loc.cant_visit_desc": "We offer discrete and secure nationwide and international shipping. Every package is fully insured from our vault to your door.",
    "loc.global_shipping": "Global Shipping",
    "loc.video_consults": "Video Consults",
    "loc.lagos_shipping": "Lagos Shipping",
    "loc.lagos_shipping_desc": "Express same-day or 1-5 day delivery via luxury courier. Secure handling guaranteed.",
    "loc.nationwide_delivery": "Nationwide Delivery",
    "loc.nationwide_delivery_desc": "3-10 business days to any major city in Nigeria with real-time tracking.",
    "loc.intl_shipping": "International Shipping",
    "loc.intl_shipping_desc": "Available upon request via specialized international carriers.",
    "loc.modal.access": "Exclusive Showroom Access",
    "loc.modal.showroom": "Showroom",
    "loc.modal.address_details": "Address Details",
    "loc.modal.copy_address": "Copy full address",
    "loc.modal.copied": "Copied",
    "loc.modal.gmaps": "Google Maps Directions",
    "loc.modal.amaps": "Apple Maps",
    "loc.active_gps": "Active GPS Coordinate",
    "loc.city.Port Harcourt": "Port Harcourt",
    "loc.address.Port Harcourt": "No 10 Warri Street, D-Line",
    "loc.city.Lagos": "Lagos",
    "loc.address.Lagos": "Tejuosho Ultramodern Market, Yaba",
    "loc.whatsapp_contact": "Contact via WhatsApp",
    
    // General / UI
    "success.copied": "Store address copied to clipboard!",
    "btn.add": "Add",

    // Footer / Extra Navigation
    "footer.newsletter.title": "Exclusive Access & Drops",
    "footer.newsletter.desc": "Never miss a restock or private collection launch. Subscribe for premier updates.",
    "footer.newsletter.placeholder": "Excellence@gold.com",
    "footer.newsletter.button": "Join the Circle",
    "footer.brand_desc": "Nigeria's premier luxury jewelry and gold investment destination. Excellence crafted in every karat.",
    "footer.quick_links": "Quick Links",
    "footer.inner_circle": "Inner Circle",
    "footer.visit_us": "Visit Us",
    "footer.link_shop": "Our Jewelry Collection",
    "footer.link_invest": "Gold Investment Bars",
    "footer.link_custom": "Custom Design Service",
    "footer.link_consult": "Book a Consultation",
    "footer.link_stores": "Our Stores",
    "footer.order_whatsapp": "Order via WhatsApp",
    "footer.delivery_guaranteed": "SECURE WORLDWIDE DELIVERY • AUTHENTICITY GUARANTEED",
    "footer.validation_format": "Please enter a valid format (e.g. name@domain.com)",
    "footer.processing_access": "Processing Access...",
    "footer.newsletter.btn_loading": "Processing Access...",
    "footer.newsletter.success": "Welcome to the Legacy. Your membership is secured.",
    "footer.newsletter.already": "You are already part of our elite circle.",
    "footer.newsletter.error": "Process interrupted. Please check your network and try again.",
    "footer.newsletter.invalid": "Please enter a valid email address.",
    "footer.services.title": "Our Legacy Services",
    "footer.services.shipping": "Secure Insured Shipping",
    "footer.services.secure": "Private Vault Custody",
    "footer.services.expert": "Expert Valuation & Assay",
    "footer.contact": "Elite Concierge",
    "footer.rights": "All rights reserved. Reserved for excellence.",

    // Home / Landing additions
    "home.why.title1": "18K / 24K",
    "home.why.desc1": "Italian Collections",
    "home.why.title2": "0% Fees",
    "home.why.desc2": "Investment Custody",
    "home.why.title3": "Dubai",
    "home.why.desc3": "Sheikh Mohammed bin Rashid Blvd, Downtown",
    "home.why.title4": "Lagos",
    "home.why.desc4": "Tejuosho Market V.I",
    "home.standard.tagline": "Wealth Preservation",
    "home.standard.title": "The 24K Standard",
    "home.standard.desc": "Gold isn't just an accessory; it's a legacy. Invest in 99.9% pure 24K gold bars to protect your wealth against inflation. From 1g to 1kg, we provide the ultimate security for your future.",
    "home.standard.btn": "Start Investing",
    "home.reviews.tagline": "Testimonials",
    "home.reviews.title": "The AU718 Experience",
    "home.cta.title": "Ready to Own Excellence?",
    "home.cta.desc": "Join thousands of satisfied clients worldwide who trust AU718 for their premium gold needs.",
    "home.cta.whatsapp": "Order via WhatsApp",
    "home.cta.instagram": "Follow on Instagram",

    // Consultation definitions
    "consult.tagline": "Private Concierge",
    "consult.title": "Bespoke Consultation",
    "consult.desc": "Experience a private viewing at our elite lounges or book a virtual session with our master designers. Your journey toward a legacy starts here.",
    "consult.prop1.title": "Authenticated Purity",
    "consult.prop1.desc": "Verify 18K to 24K investment assets with our certified gemologists.",
    "consult.prop2.title": "Private Lounge",
    "consult.prop2.desc": "Lagos & Abuja elite suites available for physical viewings.",
    "consult.hours.tagline": "Available Daily",
    "consult.hours.time": "09:00 — 18:00 WAT",
    "consult.whatsapp.tagline": "WhatsApp Direct",
    "consult.form.title": "REQUEST ACCESS",
    "consult.form.name": "Full Name",
    "consult.form.name.placeholder": "e.g. Aliko Dangote",
    "consult.form.contact": "Contact (Email or Phone)",
    "consult.form.contact.placeholder": "WhatsApp preferred",
    "consult.form.service": "Service Required",
    "consult.form.service.option1": "Bespoke Jewelry Design",
    "consult.form.service.option2": "Gold Bar Investment (In-Person)",
    "consult.form.service.option3": "Asset Authentication",
    "consult.form.service.option4": "Wholesale Partnerships",
    "consult.form.date": "Preferred Date",
    "consult.form.notes": "Concierge Notes",
    "consult.form.notes.placeholder": "Specify your carats, design vision, or investment volume...",
    "consult.form.btn.loading": "Transmitting...",
    "consult.form.btn.schedule": "Schedule Session",
    "consult.success": "Consultation request logged. Our concierge will contact you shortly.",
    "consult.error": "Process interrupted. Please contact us via WhatsApp.",

    // Custom bespoke definitions
    "custom.tagline": "You Dream. We Craft.",
    "custom.title": "Bespoke Jewelry",
    "custom.desc": "Elevate your individual style with a piece that is uniquely yours. From engagement rings to statement necklaces — we bring your imagination to life in solid gold.",
    "custom.step1.title": "Initial Concept",
    "custom.step1.desc": "Submit your idea, sketch, or reference photo to our design team.",
    "custom.step2.title": "Design Rendering",
    "custom.step2.desc": "We provide a high-fidelity 3D rendering for your approval before production.",
    "custom.step3.title": "Expert Crafting",
    "custom.step3.desc": "Our master goldsmiths hand-craft your piece using the finest materials.",
    "custom.step4.title": "Quality Audit",
    "custom.step4.desc": "Each piece undergoes rigorous testing for purity and flawless finish.",
    "custom.form.title": "Start Your Bespoke Journey",
    "custom.form.name": "Full Name",
    "custom.form.name.placeholder": "Enter your full name",
    "custom.form.type": "Jewelry Type",
    "custom.form.type.option1": "Necklace",
    "custom.form.type.option2": "Ring",
    "custom.form.type.option3": "Bracelet",
    "custom.form.type.option4": "Earrings",
    "custom.form.type.option5": "Pendant / Charm",
    "custom.form.karat": "Desired Karat",
    "custom.form.details": "Project Details",
    "custom.form.details.placeholder": "Describe your vision — style, stones, size, occasion, or any special requests...",
    "custom.form.btn": "Send Request via WhatsApp",
    "custom.quote": "\"They turned a simple sketch of mine into a family heirloom that my daughter will wear one day.\"",
    "custom.quote.author": "— Michelle A.",
    "custom.error.missing": "Please fill in your name and project details.",
    "custom.error.number": "WhatsApp number not configured.",

    // Investment definitions
    "invest.division": "Wealth Management Division",
    "invest.title1": "The Standard of",
    "invest.title2": "Generational Wealth",
    "invest.desc": "Curated LBMA-quality 24K gold bullion assets. Seamless physical custody or high-security logistics for high-net-worth investors.",
    "invest.btn.start": "Start Portfolio",
    "invest.btn.inventory": "View Inventory",
    "invest.ticker.spot": "Gold Spot (XAU/USD):",
    "it.fore.tagline": "Growth Forecast",
    "it.fore.value": "+12.4% Est.",
    "it.fore.curve": "Annual Return Curve",
    "it.calc.title": "Cost Estimator",
    "it.calc.desc": "Estimate your investment capital based on current market rates. Includes service fees and full certification.",
    "it.calc.weight": "Select Weight (Grams)",
    "it.calc.market": "Market Value",
    "it.calc.cert": "Certification & Appraisal",
    "it.calc.total": "Projected Total",
    "it.calc.lock": "Lock This Quote",
    "it.guar.tagline": "Our Guarantees",
    "it.guar.title": "Securing Your Financial Sovereignty",
    "it.benefit1.title": "Dual Purity Test",
    "it.benefit1.desc": "Every asset undergoes XRF Spectrometry and traditional assay verification.",
    "it.benefit2.title": "Vaulted Logistics",
    "it.benefit2.desc": "Private delivery via armored vehicle for all bulk institutional purchases.",
    "it.benefit3.title": "Tax Optimized",
    "it.benefit3.desc": "Consultation on tax-efficient gold holding structures for long-term wealth.",
    "it.benefit4.title": "Buy-Back Swap",
    "it.benefit4.desc": "Trade old inventory for modern bullion bars with zero liquidity delays.",
    "it.catalog.title": "Stock Catalog",
    "it.catalog.tagline": "Standard Investment Weights",
    "it.catalog.inquire": "Inquire Status",
    "it.faq.title": "Investment FAQ",
    "it.cta.tagline": "Global Standard Assurance",
    "it.cta.title": "Ready to Diversify Into Solid Purity?",
    "it.cta.btn": "Open Account",
    "it.cta.support": "Priority Support",

    // Shop definitions
    "shop.tagline": "Exquisite Purity",
    "shop.title": "Our Collection",
    "shop.desc": "Each piece is selected for its superior craftsmanship and timeless appeal. Own a piece of the sun with AU718.",
    "shop.collections": "Collections",
    "shop.purity": "Purity (Karat)",
    "shop.weight": "Weight",
    "shop.all_weights": "All weights",
    "shop.active_filters": "Active Filters:",
    "shop.clear_all": "Clear All",
    "shop.quick_view": "Quick View",
    "shop.order": "Order via WhatsApp",
    "shop.no_items": "No Items Found",
    "shop.no_items_desc": "We're currently updating our vault. Check back soon or contact us directly.",
    "shop.voices": "Voices of Excellence",
    "shop.clients": "Clients & Investors",
    "shop.complete_look": "Complete the Look",
    "shop.grade": "Grade",
    "shop.net_weight": "Net Weight",
    "shop.ready_to_ship": "Ready to Ship",
    "shop.filter_trigger": "Filter",
    "shop.refine": "Refine Selection",
    "shop.apply_filters": "Apply Filters"
  },
  de: {
    "nav.home": "Startseite",
    "nav.shop": "Geschäft",
    "nav.investment": "Investition",
    "nav.custom": "Anfertigung",
    "nav.consultation": "Beratung",
    "nav.locations": "Filialen",
    "nav.switch": "Sprache",
    
    "hero.tagline": "Der Standard des Reichtums",
    "hero.title1": "Gold besitzen.",
    "hero.title2": "Macht tragen.",
    "hero.desc": "Kuratieren der weltweit exquisitesten Goldkollektionen aus 18, 21, 22, und 24 Karat. Von handgefertigtem Modeschmuck bis hin zu renditestarken Goldbarren-Anlagen.",
    "hero.btn.jewelry": "Schmuck Shoppen",
    "hero.btn.invest": "In Gold Investieren",
    "hero.explore": "AU718 Entdecken",
    
    "feat.tagline": "Unsere Kuratierte Welt",
    "feat.title": "Besondere Kollektionen",
    "feat.view_all": "Gesamten Schmuck ansehen",
    "feat.view_col": "Kollektion ansehen",
    
    "loc.tagline": "Unsere Präsenz",
    "loc.title": "Filialen & Standorte",
    "loc.desc": "Erleben Sie das Gewicht von reinem Gold persönlich. Besuchen Sie unsere Premium-Showrooms für eine private Besichtigung und Beratung.",
    "loc.address_label": "Adresse",
    "loc.working_hours_title": "Öffnungszeiten",
    "loc.working_hours_details": "Mo - Sa: 9:00 - 18:00 Uhr",
    "loc.direct_contact": "Direktkontakt",
    "loc.get_directions": "Wegbeschreibung",
    "loc.cant_visit_title": "Sie können nicht persönlich vorbeikommen?",
    "loc.cant_visit_desc": "Wir bieten einen diskreten und sicheren nationalen sowie internationalen Versand an. Jedes Paket ist von unserem Tresor bis zu Ihrer Tür voll versichert.",
    "loc.global_shipping": "Weltweiter Versand",
    "loc.video_consults": "Video-Beratung",
    "loc.lagos_shipping": "Versand in Lagos",
    "loc.lagos_shipping_desc": "Express-Lieerung am selben Tag oder in 1-5 Tagen per Luxus-Kurier. Sichere Handhabung garantiert.",
    "loc.nationwide_delivery": "Inlandsversand",
    "loc.nationwide_delivery_desc": "3-10 Werktage in jede größere Stadt in Nigeria mit Echtzeit-Tracking.",
    "loc.intl_shipping": "Internationaler Versand",
    "loc.intl_shipping_desc": "Auf Anfrage über spezialisierte internationale Transportunternehmen erhältlich.",
    "loc.modal.access": "Exklusiver Zutritt zum Showroom",
    "loc.modal.showroom": "Ausstellungsraum",
    "loc.modal.address_details": "Adressdetails",
    "loc.modal.copy_address": "Vollständige Adresse kopieren",
    "loc.modal.copied": "Kopiert",
    "loc.modal.gmaps": "Google Maps Route",
    "loc.modal.amaps": "Apple Maps Route",
    "loc.active_gps": "Aktive GPS-Koordinate",
    "loc.city.Port Harcourt": "Port Harcourt",
    "loc.address.Port Harcourt": "Warri Str. Nr. 10, D-Line",
    "loc.city.Lagos": "Lagos",
    "loc.address.Lagos": "Tejuosho Ultramodern Markt, Yaba",
    "loc.whatsapp_contact": "Über WhatsApp kontaktieren",
    
    "success.copied": "Geschäftsadresse in die Zwischenablage kopiert!",
    "btn.add": "Hinzufügen",

    // Footer
    "footer.newsletter.title": "Exklusiver Zugang & Drops",
    "footer.newsletter.desc": "Verpassen Sie nie wieder eine Auffüllung oder die Einführung privater Kollektionen. Abonnieren Sie für Premium-Updates.",
    "footer.newsletter.placeholder": "Exzellenz@gold.com",
    "footer.newsletter.button": "Tritt dem Kreis bei",
    "footer.brand_desc": "Nigerias führende Luxusschmuck- und Goldinvestment-Destination. Exzellenz in jedem Karat.",
    "footer.quick_links": "Schnelllinks",
    "footer.inner_circle": "Innerer Kreis",
    "footer.visit_us": "Besuchen Sie uns",
    "footer.link_shop": "Unsere Schmuckkollektion",
    "footer.link_invest": "Goldbarren-Anlage",
    "footer.link_custom": "Anfertigungsservice",
    "footer.link_consult": "Beratung buchen",
    "footer.link_stores": "Unsere Filialen",
    "footer.order_whatsapp": "Per WhatsApp bestellen",
    "footer.delivery_guaranteed": "SICHERE WELTWEITE LIEFERUNG • GARANTIERTE ECHTHEIT",
    "footer.validation_format": "Bitte geben Sie ein gültiges Format ein (z. B. name@domain.com)",
    "footer.processing_access": "Zugang wird verarbeitet...",
    "footer.newsletter.btn_loading": "Zugang wird verarbeitet...",
    "footer.newsletter.success": "Willkommen im Vermächtnis. Ihre Mitgliedschaft ist gesichert.",
    "footer.newsletter.already": "Sie sind bereits Teil unseres Elite-Kreises.",
    "footer.newsletter.error": "Vorgang unterbrochen. Bitte überprüfen Sie Ihr Netzwerk.",
    "footer.newsletter.invalid": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "footer.services.title": "Unsere Legacy-Dienstleistungen",
    "footer.services.shipping": "Sicherer Versicherter Versand",
    "footer.services.secure": "Private Tresorverwahrung",
    "footer.services.expert": "Expertenbewertung & Analyse",
    "footer.contact": "Elite Concierge",
    "footer.rights": "Alle Rechte vorbehalten. Für Exzellenz reserviert.",

    // Home
    "home.why.title1": "18K / 24K",
    "home.why.desc1": "Italienische Kollektionen",
    "home.why.title2": "0% Gebühren",
    "home.why.desc2": "Depotverwahrung",
    "home.why.title3": "Dubai",
    "home.why.desc3": "Sheikh Mohammed bin Rashid Blvd, Downtown",
    "home.why.title4": "Lagos",
    "home.why.desc4": "Tejuosho Market V.I",
    "home.standard.tagline": "Vermögensschutz",
    "home.standard.title": "Der 24K-Standard",
    "home.standard.desc": "Gold ist nicht einfach ein Accessoire; es ist ein Vermächtnis. Investieren Sie in 99,9% reine 24K-Goldbarren, um Ihr Vermögen vor Inflation zu schützen. Von 1g bis 1kg bieten wir die ultimative Sicherheit für Ihre Zukunft.",
    "home.standard.btn": "Jetzt Investieren",
    "home.reviews.tagline": "Erfahrungsberichte",
    "home.reviews.title": "Das AU718-Erlebnis",
    "home.cta.title": "Bereit für Exzellenz?",
    "home.cta.desc": "Schließen Sie sich Tausenden von zufriedenen Kunden weltweit an, die AU718 für ihre erstklassigen Goldbedürfnisse vertrauen.",
    "home.cta.whatsapp": "Per WhatsApp bestellen",
    "home.cta.instagram": "Auf Instagram folgen",

    // Consultation
    "consult.tagline": "Privater Concierge",
    "consult.title": "Persönliche Beratung",
    "consult.desc": "Erleben Sie eine private Besichtigung in unseren Elite-Lounges oder buchen Sie eine virtuelle Sitzung mit unseren Meisterdesignern. Ihre Reise zu einem Vermächtnis beginnt hier.",
    "consult.prop1.title": "Authentifizierte Reinheit",
    "consult.prop1.desc": "Überprüfen Sie 18- bis 24-Karat-Anlagegüter mit unseren zertifizierten Gemmologen.",
    "consult.prop2.title": "Private Lounge",
    "consult.prop2.desc": "Elite-Suiten in Lagos und Abuja stehen für physische Besichtigungen zur Verfügung.",
    "consult.hours.tagline": "Täglich Verfügbar",
    "consult.hours.time": "09:00 — 18:00 WAT",
    "consult.whatsapp.tagline": "Direkt per WhatsApp",
    "consult.form.title": "ZUGANG ANFORDERN",
    "consult.form.name": "Vollständiger Name",
    "consult.form.name.placeholder": "z.B. Aliko Dangote",
    "consult.form.contact": "Kontakt (E-Mail oder Telefon)",
    "consult.form.contact.placeholder": "WhatsApp bevorzugt",
    "consult.form.service": "Benötigter Service",
    "consult.form.service.option1": "Maßgeschneidertes Schmuckdesign",
    "consult.form.service.option2": "Goldbarren-Investition (Persönlich)",
    "consult.form.service.option3": "Überprüfung der Reinheit",
    "consult.form.service.option4": "Großhandelspartnerschaften",
    "consult.form.date": "Bevorzugtes Datum",
    "consult.form.notes": "Concierge-Notizen",
    "consult.form.notes.placeholder": "Geben Sie Ihre Karat, Designvorstellung oder Ihr Investitionsvolumen an...",
    "consult.form.btn.loading": "Übermittlung...",
    "consult.form.btn.schedule": "Termin vereinbaren",
    "consult.success": "Beratungsanfrage registriert. Unser Concierge wird sich in Kürze mit Ihnen in Verbindung setzen.",
    "consult.error": "Vorgang unterbrochen. Bitte kontaktieren Sie uns per WhatsApp.",

    // Custom
    "custom.tagline": "Sie träumen. Wir erschaffen.",
    "custom.title": "Maßgeschneiderter Schmuck",
    "custom.desc": "Unterstreichen Sie Ihren individuellen Stil mit einem Stück, das einzigartig Ihnen gehört. Von Verlobungsringen bis zu Statement-Halsketten – wir erwecken Ihre Fantasie in solidem Gold zum Leben.",
    "custom.step1.title": "Erstes Konzept",
    "custom.step1.desc": "Senden Sie Ihre Idee, Skizze oder Ihr Referenzfoto an unser Designteam.",
    "custom.step2.title": "Design-Rendering",
    "custom.step2.desc": "Wir liefern ein hochauflösendes 3D-Rendering zur Genehmigung vor der Produktion.",
    "custom.step3.title": "Meisterhaftes Handwerk",
    "custom.step3.desc": "Unsere Goldschmiedemeister fertigen Ihr Stück in Handarbeit aus feinsten Materialien.",
    "custom.step4.title": "Qualitätsprüfung",
    "custom.step4.desc": "Jedes Stück wird einer strengen Reinheitsprüfung und einem makellosen Finish unterzogen.",
    "custom.form.title": "Starten Sie Ihre Maßanfertigung",
    "custom.form.name": "Vollständiger Name",
    "custom.form.name.placeholder": "Geben Sie Ihren vollständigen Namen ein",
    "custom.form.type": "Schmuckart",
    "custom.form.type.option1": "Halskette",
    "custom.form.type.option2": "Ring",
    "custom.form.type.option3": "Armband",
    "custom.form.type.option4": "Ohrringe",
    "custom.form.type.option5": "Anhänger / Charm",
    "custom.form.karat": "Gewünschte Karatzahl",
    "custom.form.details": "Projektdetails",
    "custom.form.details.placeholder": "Beschreiben Sie Ihre Vorstellung – Stil, Steine, Größe, Anlass oder spezielle Wünsche...",
    "custom.form.btn": "Anfrage über WhatsApp senden",
    "custom.quote": "\"Sie haben eine einfache Skizze von mir in ein Familienerbstück verwandelt, das meine Tochter eines Tages tragen wird.\"",
    "custom.quote.author": "— Michelle A.",
    "custom.error.missing": "Bitte tragen Sie Ihren Namen und die Projektdetails ein.",
    "custom.error.number": "WhatsApp-Nummer nicht konfiguriert.",

    // Investment
    "invest.division": "Abteilung für Vermögensverwaltung",
    "invest.title1": "Der Standard für",
    "invest.title2": "Generationenübergreifenden Wohlstand",
    "invest.desc": "Kuratierte 24K Goldbarren in LBMA-Qualität. Nahtlose physische Verwahrung oder hochpräzise Logistik für anspruchsvolle Anleger.",
    "invest.btn.start": "Portfolio starten",
    "invest.btn.inventory": "Bestand ansehen",
    "invest.ticker.spot": "Gold-Spotpreis (XAU/USD):",
    "it.fore.tagline": "Wachstumsprognose",
    "it.fore.value": "+12,4% geschatzt",
    "it.fore.curve": "Jährliche Ertragskurve",
    "it.calc.title": "Kostenschätzer",
    "it.calc.desc": "Schätzen Sie Ihr Investitionskapital basierend auf aktuellen Marktkursen. Inklusive Servicegebühren und vollständiger Zertifizierung.",
    "it.calc.weight": "Gewicht wählen (Gramm)",
    "it.calc.market": "Marktwert",
    "it.calc.cert": "Zertifizierung & Bewertung",
    "it.calc.total": "Voraussichtliche Summe",
    "it.calc.lock": "Dieses Angebot sichern",
    "it.guar.tagline": "Unsere Garantien",
    "it.guar.title": "Sicherung Ihrer finanziellen Souveränität",
    "it.benefit1.title": "Zweifacher Reinheitstest",
    "it.benefit1.desc": "Jeder Vermögenswert wird einer XRF-Spektrometrie und einer traditionellen Prüfung unterzogen.",
    "it.benefit2.title": "Gesicherte Logistik",
    "it.benefit2.desc": "Private Lieferung per gepanzertem Fahrzeug für alle institutionellen Großkäufe.",
    "it.benefit3.title": "Steuerlich Optimiert",
    "it.benefit3.desc": "Beratung zu steuereffizienten Goldbesitzstrukturen für langfristiges Vermögen.",
    "it.benefit4.title": "Rückkauf-Tausch",
    "it.benefit4.desc": "Tauschen Sie Ihren alten Bestand sofort und ohne Liquiditätsverzögerung gegen moderne Barren.",
    "it.catalog.title": "Katalog",
    "it.catalog.tagline": "Standard-Investmentgewichte",
    "it.catalog.inquire": "Status anfragen",
    "it.faq.title": "Investitions-FAQ",
    "it.cta.tagline": "Globale Standard-Garantie",
    "it.cta.title": "Bereit, in solide Reinheit zu investieren?",
    "it.cta.btn": "Konto eröffnen",
    "it.cta.support": "Prioritäts-Support",

    // Shop
    "shop.tagline": "Exquisite Reinheit",
    "shop.title": "Unsere Kollektion",
    "shop.desc": "Jedes Stück ist aufgrund seiner erstklassigen Handwerkskunst und zeitlosen Eleganz ausgewählt. Besitzen Sie ein Stück der Sonne mit AU718.",
    "shop.collections": "Kollektionen",
    "shop.purity": "Reinheit (Karat)",
    "shop.weight": "Gewicht",
    "shop.all_weights": "Alle Gewichte",
    "shop.active_filters": "Aktive Filter:",
    "shop.clear_all": "Alle löschen",
    "shop.quick_view": "Schnellansicht",
    "shop.order": "Über WhatsApp bestellen",
    "shop.no_items": "Keine Artikel Gefunden",
    "shop.no_items_desc": "Wir aktualisieren derzeit unseren Tresor. Bitte schauen Sie bald wieder vorbei oder kontaktieren Sie uns direkt.",
    "shop.voices": "Stimmen der Exzellenz",
    "shop.clients": "Kunden & Investoren",
    "shop.complete_look": "Den Look vervollständigen",
    "shop.grade": "Qualität",
    "shop.net_weight": "Nettogewicht",
    "shop.ready_to_ship": "Versandfertig",
    "shop.filter_trigger": "Filter",
    "shop.refine": "Auswahl verfeinern",
    "shop.apply_filters": "Filter anwenden"
  },
  fr: {
    "nav.home": "Accueil",
    "nav.shop": "Boutique",
    "nav.investment": "Investissement",
    "nav.custom": "Sur Mesure",
    "nav.consultation": "Consultation",
    "nav.locations": "Boutiques",
    "nav.switch": "Langue",
    
    "hero.tagline": "La Norme de la Richesse",
    "hero.title1": "Posséder l'Or.",
    "hero.title2": "Porter le Pouvoir.",
    "hero.desc": "Sélection des collections d'or 18K, 21K, 22K et 24K les plus exquises au monde. Des bijoux fantaisie artisanaux aux investissements en lingots d'or à haut rendement.",
    "hero.btn.jewelry": "Acheter des Bijoux",
    "hero.btn.invest": "Investir dans l'Or",
    "hero.explore": "Explorer AU718",
    
    "feat.tagline": "Notre Monde Sélectionné",
    "feat.title": "Collections Vedettes",
    "feat.view_all": "Voir Tous les Bijoux",
    "feat.view_col": "Voir la Collection",
    
    "loc.tagline": "Notre Présence",
    "loc.title": "Boutiques et Showrooms",
    "loc.desc": "Découvrez le poids de l'or pur en personne. Visitez nos showrooms exclusifs pour une visite et une consultation privées.",
    "loc.address_label": "Adresse",
    "loc.working_hours_title": "Heures d'ouverture",
    "loc.working_hours_details": "Lun - Sam: 9h00 - 18h00",
    "loc.direct_contact": "Contact Direct",
    "loc.get_directions": "Obtenir l'itinéraire",
    "loc.cant_visit_title": "Vous ne pouvez pas vous déplacer ?",
    "loc.cant_visit_desc": "Nous proposons des livraisons discrètes et sécurisées au niveau national et international. Chaque colis est entièrement assuré de notre coffre-fort à votre porte.",
    "loc.global_shipping": "Livraison Mondiale",
    "loc.video_consults": "Consultation Vidéo",
    "loc.lagos_shipping": "Livraison à Lagos",
    "loc.lagos_shipping_desc": "Livraison express le jour même ou en 1 à 5 jours via coursier de luxe. Manipulation sécurisée garantie.",
    "loc.nationwide_delivery": "Livraison Nationale",
    "loc.nationwide_delivery_desc": "3 à 10 jours ouvrables vers n'importe quelle grande ville du Nigeria avec suivi en temps réel.",
    "loc.intl_shipping": "Livraison Internationale",
    "loc.intl_shipping_desc": "Disponible sur demande via des transporteurs internationaux spécialisés.",
    "loc.modal.access": "Accès Exclusif au Showroom",
    "loc.modal.showroom": "Showroom",
    "loc.modal.address_details": "Détails de l'adresse",
    "loc.modal.copy_address": "Copier l'adresse complète",
    "loc.modal.copied": "Copié",
    "loc.modal.gmaps": "Itinéraire Google Maps",
    "loc.modal.amaps": "Itinéraire Apple Maps",
    "loc.active_gps": "Coordonnée GPS Active",
    "loc.city.Port Harcourt": "Port Harcourt",
    "loc.address.Port Harcourt": "No 10 Warri Street, D-Line",
    "loc.city.Lagos": "Lagos",
    "loc.address.Lagos": "Marché ultramoderne de Tejuosho, Yaba",
    "loc.whatsapp_contact": "Contact via WhatsApp",
    
    "success.copied": "Adresse de la boutique copiée dans le presse-papiers!",
    "btn.add": "Ajouter",

    // Footer
    "footer.newsletter.title": "Accès exclusif & Lancements",
    "footer.newsletter.desc": "Ne manquez jamais un réapprovisionnement ou le lancement d'une collection privée. Abonnez-vous aux mises à jour.",
    "footer.newsletter.placeholder": "Excellence@gold.com",
    "footer.newsletter.button": "Rejoindre le Cercle",
    "footer.brand_desc": "La première destination de bijoux de luxe et d'investissement en or au Nigeria. L'excellence incarnée dans chaque carat.",
    "footer.quick_links": "Liens Rapides",
    "footer.inner_circle": "Cercle Restreint",
    "footer.visit_us": "Visitez-nous",
    "footer.link_shop": "Our Jewelry Collection",
    "footer.link_invest": "Gold Investment Bars",
    "footer.link_custom": "Custom Design Service",
    "footer.link_consult": "Book a Consultation",
    "footer.link_stores": "Our Stores",
    "footer.order_whatsapp": "Commander par WhatsApp",
    "footer.delivery_guaranteed": "LIVRAISON SÉCURISÉE MONDIALE • AUTHENTICITÉ GARANTIE",
    "footer.validation_format": "Veuillez entrer un format valide (ex. nom@domaine.com)",
    "footer.processing_access": "Traitement de l'accès...",
    "footer.newsletter.btn_loading": "Traitement de l'accès...",
    "footer.newsletter.success": "Bienvenue dans l'Héritage. Votre adhésion est sécurisée.",
    "footer.newsletter.already": "Vous faites déjà partie de notre cercle d'élite.",
    "footer.newsletter.error": "Processus interrompu. Veuillez vérifier votre réseau.",
    "footer.newsletter.invalid": "Veuillez entrer une adresse e-mail valide.",
    "footer.services.title": "Nos Services Prestigieux",
    "footer.services.shipping": "Livraison Sécurisée et Assurée",
    "footer.services.secure": "Garde en Coffre Privé",
    "footer.services.expert": "Évaluation et Expertise d'Or",
    "footer.contact": "Conciergerie d'Élite",
    "footer.rights": "Tous droits réservés. Écrit pour l'excellence.",

    // Home
    "home.why.title1": "18K / 24K",
    "home.why.desc1": "Collections Italiennes",
    "home.why.title2": "0% Frais",
    "home.why.desc2": "Garde d'Investissement",
    "home.why.title3": "Dubaï",
    "home.why.desc3": "Sheikh Mohammed bin Rashid Blvd, Downtown",
    "home.why.title4": "Lagos",
    "home.why.desc4": "Tejuosho Market V.I",
    "home.standard.tagline": "Préservation du Patrimoine",
    "home.standard.title": "La Norme du 24K",
    "home.standard.desc": "L'or n'est pas seulement un accessoire; c'est un héritage. Investissez dans des lingots d'or 24K purs à 99,9% pour protéger votre patrimoine contre l'inflation. De 1g à 1kg, nous fournissons la sécurité ultime pour votre avenir.",
    "home.standard.btn": "Commencer à Investir",
    "home.reviews.tagline": "Témoignages",
    "home.reviews.title": "L'Expérience AU718",
    "home.cta.title": "Prêt à Poséder l'Excellence ?",
    "home.cta.desc": "Rejoignez des milliers de clients satisfaits à travers le monde qui font confiance à AU718 pour leurs besoins en or premium.",
    "home.cta.whatsapp": "Commander via WhatsApp",
    "home.cta.instagram": "Nous suivre sur Instagram",

    // Consultation
    "consult.tagline": "Concierge Privé",
    "consult.title": "Consultation Privée",
    "consult.desc": "Profitez d'une visite privée dans nos salons d'élite ou réservez une session virtuelle avec nos maîtres designers. Votre voyage vers un héritage précieux commence ici.",
    "consult.prop1.title": "Pureté Authentifiée",
    "consult.prop1.desc": "Vérifiez vos lingots et bijoux en or 18K à 24K avec nos gemmologues certifiés.",
    "consult.prop2.title": "Salon Privé",
    "consult.prop2.desc": "Des suites d'élite à Lagos et Abuja sont prêtes pour des visites physiques.",
    "consult.hours.tagline": "Disponible Tous les Jours",
    "consult.hours.time": "09h00 — 18h00 WAT",
    "consult.whatsapp.tagline": "WhatsApp Direct",
    "consult.form.title": "DEMANDER UN ACCÈS",
    "consult.form.name": "Nom complet",
    "consult.form.name.placeholder": "ex. Aliko Dangote",
    "consult.form.contact": "Contact (E-mail ou Téléphone)",
    "consult.form.contact.placeholder": "WhatsApp de préférence",
    "consult.form.service": "Service requis",
    "consult.form.service.option1": "Conception de bijoux sur mesure",
    "consult.form.service.option2": "Investissement en lingots d'or (En personne)",
    "consult.form.service.option3": "Authentification d'actifs",
    "consult.form.service.option4": "Partenariats de gros",
    "consult.form.date": "Date souhaitée",
    "consult.form.notes": "Notes pour la conciergerie",
    "consult.form.notes.placeholder": "Précisez vos carats, votre style de design ou votre volume d'investissement...",
    "consult.form.btn.loading": "Envoi en cours...",
    "consult.form.btn.schedule": "Planifier la session",
    "consult.success": "Demande de consultation enregistrée. Notre concierge vous contactera sous peu.",
    "consult.error": "Processus interrompu. Veuillez nous contacter directement via WhatsApp.",

    // Custom
    "custom.tagline": "Vous rêvez. Nous créons.",
    "custom.title": "Bijoux Sur Mesure",
    "custom.desc": "Affirmez votre style individuel avec une pièce qui vous ressemble exclusivement. Des bagues de fiançailles aux colliers majestueux, nous donnons vie à votre vision dans l'or massif.",
    "custom.step1.title": "Concept Initial",
    "custom.step1.desc": "Soumettez votre idée, croquis ou photo de référence à notre équipe de design.",
    "custom.step2.title": "Rendu de Conception",
    "custom.step2.desc": "Nous fournissons un rendu 3D haute fidélité pour votre approbation avant la fabrication.",
    "custom.step3.title": "Artisanat d'Élite",
    "custom.step3.desc": "Nos maîtres orfèvres façonnent votre pièce à la main avec les matériaux les plus fins.",
    "custom.step4.title": "Contrôle Qualité",
    "custom.step4.desc": "Chaque création subit des tests rigoureux de pureté et de finition.",
    "custom.form.title": "Commencer votre Voyage Sur Mesure",
    "custom.form.name": "Nom complet",
    "custom.form.name.placeholder": "Saisissez votre nom complet",
    "custom.form.type": "Type de bijou",
    "custom.form.type.option1": "Collier",
    "custom.form.type.option2": "Bague",
    "custom.form.type.option3": "Bracelet",
    "custom.form.type.option4": "Boucles d'oreilles",
    "custom.form.type.option5": "Pendentif / Charme",
    "custom.form.karat": "Carat souhaité",
    "custom.form.details": "Détails du projet",
    "custom.form.details.placeholder": "Décrivez votre idée — style, pierres, taille, occasion spéciale, ou demande particulière...",
    "custom.form.btn": "Envoyer la demande via WhatsApp",
    "custom.quote": "\"Ils ont transformé mon simple croquis en un héritage familial que ma fille portera un jour.\"",
    "custom.quote.author": "— Michelle A.",
    "custom.error.missing": "Veuillez remplir votre nom et les détails du projet.",
    "custom.error.number": "Numéro WhatsApp non configuré.",

    // Investment
    "invest.division": "Division de Gestion de Patrimoine",
    "invest.title1": "La Norme du",
    "invest.title2": "Patrimoine Générationnel",
    "invest.desc": "Or d'investissement 24K de qualité LBMA. Garde physique fluide ou logistique haute sécurité pour stock de grande envergure.",
    "invest.btn.start": "Créer un Portefeuille",
    "invest.btn.inventory": "Voir le Stock",
    "invest.ticker.spot": "Cours de l'Or (XAU/USD) :",
    "it.fore.tagline": "Prévision de Croissance",
    "it.fore.value": "+12,4% Est.",
    "it.fore.curve": "Courbe de Rendement Annuel",
    "it.calc.title": "Estimateur de Coût",
    "it.calc.desc": "Estimez votre capital d'investissement basé sur les tarifs du marché. Inclut les frais de service et la certification complète.",
    "it.calc.weight": "Sélectionner le poids (Grammes)",
    "it.calc.market": "Valeur du Marché",
    "it.calc.cert": "Certification & Évaluation",
    "it.calc.total": "Total Prévisionnel",
    "it.calc.lock": "Bloquer ce Tarif",
    "it.guar.tagline": "Nos Garanties",
    "it.guar.title": "Sécuriser votre Souveraineté Financière",
    "it.benefit1.title": "Double Test de Pureté",
    "it.benefit1.desc": "Chaque lingot est soumis à la spectrométrie XRF et à la vérification par essai traditionnel.",
    "it.benefit2.title": "Logistique Blindée",
    "it.benefit2.desc": "Livraison sécurisée avec escorte blindée pour tous les achats professionnels volumineux.",
    "it.benefit3.title": "Optimisation Fiscale",
    "it.benefit3.desc": "Conseil sur les structures fiscales de détention d'or pour vos actifs à long terme.",
    "it.benefit4.title": "Reprise et Échange",
    "it.benefit4.desc": "Échangez vos vieux bijoux contre des lingots d'or d'investissement sans frais de liquidité.",
    "it.catalog.title": "Catalogue",
    "it.catalog.tagline": "Poids d'Investissement Standards",
    "it.catalog.inquire": "Demander le statut",
    "it.faq.title": "FAQ Investissements",
    "it.cta.tagline": "Assurance de Niveau International",
    "it.cta.title": "Prêt à sécuriser votre avenir dans la pureté ?",
    "it.cta.btn": "Ouvrir un Compte",
    "it.cta.support": "Assistance Prioritaire",

    // Shop
    "shop.tagline": "Pureté Exquise",
    "shop.title": "Notre Collection",
    "shop.desc": "Chaque modèle est sélectionné pour son artisanat d'art et son design intemporel. Possédez une parcelle de soleil avec AU718.",
    "shop.collections": "Collections",
    "shop.purity": "Pureté (Carat)",
    "shop.weight": "Poids",
    "shop.all_weights": "Tous les poids",
    "shop.active_filters": "Filtres actifs :",
    "shop.clear_all": "Effacer tout",
    "shop.quick_view": "Aperçu rapide",
    "shop.order": "Commander via WhatsApp",
    "shop.no_items": "Aucun Article Trouvé",
    "shop.no_items_desc": "Nous mettons à jour notre coffre en ce moment. Revenez bientôt ou contactez-nous directement.",
    "shop.voices": "Voix de l'Excellence",
    "shop.clients": "Clients & Investisseurs",
    "shop.complete_look": "Compléter le Look",
    "shop.grade": "Pureté",
    "shop.net_weight": "Poids Net",
    "shop.ready_to_ship": "Prêt à être livré",
    "shop.filter_trigger": "Filtrer",
    "shop.refine": "Affiner la sélection",
    "shop.apply_filters": "Appliquer les filtres"
  },
  es: {
    "nav.home": "Inicio",
    "nav.shop": "Tienda",
    "nav.investment": "Inversión",
    "nav.custom": "Personalizado",
    "nav.consultation": "Consulta",
    "nav.locations": "Ubicaciones",
    "nav.switch": "Idioma",
    
    "hero.tagline": "El Estándar de la Riqueza",
    "hero.title1": "Poseer Oro.",
    "hero.title2": "Viste Poder.",
    "hero.desc": "Curando las colecciones de oro de 18K, 21K, 22K y 24K más exquisitas del mundo. Desde joyería de moda artesanal hasta inversiones en lingotes de oro de alto rendimiento.",
    "hero.btn.jewelry": "Comprar Joyería",
    "hero.btn.invest": "Invertir en Oro",
    "hero.explore": "Explorar AU718",
    
    "feat.tagline": "Nuestro Mundo Curado",
    "feat.title": "Colecciones Destacadas",
    "feat.view_all": "Ver Toda la Joyería",
    "feat.view_col": "Ver Colección",
    
    "loc.tagline": "Nuestra Presencia",
    "loc.title": "Ubicaciones de Tiendas",
    "loc.desc": "Experimente el peso del oro puro en persona. Visite nuestros prestigiosos showrooms para visitas privadas y asesoramiento exclusivo.",
    "loc.address_label": "Dirección",
    "loc.working_hours_title": "Horarios de Apertura",
    "loc.working_hours_details": "Lun - Sáb: 9:00 AM - 6:00 PM",
    "loc.direct_contact": "Contacto Directo",
    "loc.get_directions": "Obtener Direcciones",
    "loc.cant_visit_title": "¿No puede visitarnos en persona?",
    "loc.cant_visit_desc": "Ofrecemos envíos discretos y seguros a nivel nacional e internacional. Cada paquete está completamente asegurado desde nuestra bóveda hasta su puerta.",
    "loc.global_shipping": "Envío Global",
    "loc.video_consults": "Consultas en Video",
    "loc.lagos_shipping": "Envío en Lagos",
    "loc.lagos_shipping_desc": "Envío exprés el mismo día o de 1 a 5 días mediante mensajería de lujo. Manipulación segura garantizada.",
    "loc.nationwide_delivery": "Envío Nacional",
    "loc.nationwide_delivery_desc": "3-10 días hábiles a cualquier ciudad importante de de Nigeria con seguimiento en tiempo real.",
    "loc.intl_shipping": "Envíos Internacionales",
    "loc.intl_shipping_desc": "Disponible bajo solicitud a través de transportistas internacionales especializados.",
    "loc.modal.access": "Acceso Exclusivo al Showroom",
    "loc.modal.showroom": "Showroom",
    "loc.modal.address_details": "Detalles de la Dirección",
    "loc.modal.copy_address": "Copiar dirección completa",
    "loc.modal.copied": "Copiado",
    "loc.modal.gmaps": "Direcciones de Google Maps",
    "loc.modal.amaps": "Apple Maps",
    "loc.active_gps": "Coordenada GPS Activa",
    "loc.city.Port Harcourt": "Port Harcourt",
    "loc.address.Port Harcourt": "No 10 Warri Street, D-Line",
    "loc.city.Lagos": "Lagos",
    "loc.address.Lagos": "Mercado ultramoderno de Tejuosho, Yaba",
    "loc.whatsapp_contact": "Contactar por WhatsApp",
    
    "success.copied": "¡Dirección de la tienda copiada al portapapeles!",
    "btn.add": "Añadir",

    // Footer
    "footer.newsletter.title": "Acceso Exclusivo & Drops",
    "footer.newsletter.desc": "No te pierdas ningún reabastecimiento o lanzamiento de colecciones privadas. Regístrate para recibir novedades.",
    "footer.newsletter.placeholder": "Excelencia@gold.com",
    "footer.newsletter.button": "Unirse al Círculo",
    "footer.brand_desc": "El principal destino de joyería de lujo e inversión en oro de Nigeria. Excelencia plasmada en cada quilate.",
    "footer.quick_links": "Enlaces Rápidos",
    "footer.inner_circle": "Círculo Privado",
    "footer.visit_us": "Visítenos",
    "footer.link_shop": "Nuestra Colección de Joyas",
    "footer.link_invest": "Lingotes de Inversión en Oro",
    "footer.link_custom": "Servicio de Diseño Personalizado",
    "footer.link_consult": "Reservar una Consulta",
    "footer.link_stores": "Nuestras Tiendas",
    "footer.order_whatsapp": "Ordenar por WhatsApp",
    "footer.delivery_guaranteed": "ENVÍO SEGURO A TODO EL MUNDO • AUTENTICIDAD GARANTIZADA",
    "footer.validation_format": "Por favor ingrese un formato válido (ej. nombre@dominio.com)",
    "footer.processing_access": "Procesando Acceso...",
    "footer.newsletter.btn_loading": "Procesando Acceso...",
    "footer.newsletter.success": "Bienvenido al Legado. Su membresía está asegurada.",
    "footer.newsletter.already": "Ya forma parte de nuestro círculo de élite.",
    "footer.newsletter.error": "Proceso interrumpido. Por favor compruebe su red.",
    "footer.newsletter.invalid": "Por favor ingrese un correo electrónico válido.",
    "footer.services.title": "Servicios Legendarios",
    "footer.services.shipping": "Envío Asegurado y Protegido",
    "footer.services.secure": "Custodia en Bóvedas Privadas",
    "footer.services.expert": "Valoración y Ensayo Expertos",
    "footer.contact": "Conserjería de Élite",
    "footer.rights": "Todos los derechos reservados. Reservado para la excelencia.",

    // Home
    "home.why.title1": "18K / 24K",
    "home.why.desc1": "Colecciones Italianas",
    "home.why.title2": "0% Comisiones",
    "home.why.desc2": "Custodia de Inversión",
    "home.why.title3": "Dubái",
    "home.why.desc3": "Sheikh Mohammed bin Rashid Blvd, Downtown",
    "home.why.title4": "Lagos",
    "home.why.desc4": "Tejuosho Market V.I",
    "home.standard.tagline": "Preservación de la Riqueza",
    "home.standard.title": "El Estándar 24K",
    "home.standard.desc": "El oro no es solo un accesorio; es un legado indestructible. Invierte en lingotes de oro de 24K con un 99.9% de pureza para proteger tus ahorros frente a la inflación. Desde 1g hasta 1kg, aseguramos tu futuro.",
    "home.standard.btn": "Comenzar a Invertir",
    "home.reviews.tagline": "Testimonios",
    "home.reviews.title": "La Experiencia AU718",
    "home.cta.title": "¿Listo para poseer excelencia?",
    "home.cta.desc": "Súmate a miles de clientes selectos de todo el mundo que confían en AU718 para proteger su patrimonio.",
    "home.cta.whatsapp": "Pedir por WhatsApp",
    "home.cta.instagram": "Seguir en Instagram",

    // Consultation
    "consult.tagline": "Conserje Privado",
    "consult.title": "Consulta Exclusiva",
    "consult.desc": "Viva una experiencia de visualización privada en nuestros exclusivos salones o reserve una sesión virtual con nuestros diseñadores. Tu camino hacia el legado inicia aquí.",
    "consult.prop1.title": "Pureza Auténtica",
    "consult.prop1.desc": "Verifique activos en oro de 18K a 24K con nuestros gemólogos certificados.",
    "consult.prop2.title": "Salones Privados",
    "consult.prop2.desc": "Suites exclusivas en Lagos y Abuja listas para visitas físicas de alta confidencialidad.",
    "consult.hours.tagline": "Atención Diaria",
    "consult.hours.time": "09:00 — 18:00 WAT",
    "consult.whatsapp.tagline": "Línea WhatsApp",
    "consult.form.title": "SOLICITAR ACCESO",
    "consult.form.name": "Nombre completo",
    "consult.form.name.placeholder": "ej. Aliko Dangote",
    "consult.form.contact": "Contacto (Email o Teléfono)",
    "consult.form.contact.placeholder": "WhatsApp preferible",
    "consult.form.service": "Servicio requerido",
    "consult.form.service.option1": "Diseño de joyería personalizado",
    "consult.form.service.option2": "Inversión en lingotes de oro (En persona)",
    "consult.form.service.option3": "Autenticación de pureza",
    "consult.form.service.option4": "Alianzas mayoristas",
    "consult.form.date": "Fecha preferida",
    "consult.form.notes": "Notas del cliente",
    "consult.form.notes.placeholder": "Especifique quilates, idea de diseño y volumen aproximado de inversión...",
    "consult.form.btn.loading": "Transmitiendo...",
    "consult.form.btn.schedule": "Agendar Sesión",
    "consult.success": "Solicitud registrada. Nuestro conserje VIP se comunicará con usted en breve.",
    "consult.error": "Proceso interrumpido. Por favor, contáctenos directamente por WhatsApp.",

    // Custom
    "custom.tagline": "Tú sueñas. Nosotros creamos.",
    "custom.title": "Joyería a Medida",
    "custom.desc": "Eleve su estilo personal con una obra maestra de diseño único. Desde anillos de compromiso hasta collares de gala: fundimos sus sueños en oro real.",
    "custom.step1.title": "Bosquejo Inicial",
    "custom.step1.desc": "Comparta sus ideas, referencias o bocetos para ponerlos en manos de los diseñadores.",
    "custom.step2.title": "Modelado 3D",
    "custom.step2.desc": "Generamos un modelado digital exacto para obtener su plena conformidad antes de la forja.",
    "custom.step3.title": "Hecho a Mano",
    "custom.step3.desc": "Artesanos de tradición orfebre dan vida a la pieza forjando metales selectos.",
    "custom.step4.title": "Certificación",
    "custom.step4.desc": "Cada pieza se examina de manera estricta para garantizar un acabado impecable de máxima pureza.",
    "custom.form.title": "Comience su camino de distinción",
    "custom.form.name": "Nombre completo",
    "custom.form.name.placeholder": "Ingrese su nombre completo",
    "custom.form.type": "Tipo de joya",
    "custom.form.type.option1": "Collar",
    "custom.form.type.option2": "Anillo",
    "custom.form.type.option3": "Pulsera",
    "custom.form.type.option4": "Pendientes",
    "custom.form.type.option5": "Colgante / Amuleto",
    "custom.form.karat": "Quilates deseados",
    "custom.form.details": "Detalles del proyecto",
    "custom.form.details.placeholder": "Describa su visión de joyería — estilo, piedras, tamaño, ocasión de uso o indicaciones especiales...",
    "custom.form.btn": "Enviar solicitud vía WhatsApp",
    "custom.quote": "\"Lograron transformar un simple boceto a mano alzada en una valiosa reliquia familiar para las futuras generaciones.\"",
    "custom.quote.author": "— Michelle A.",
    "custom.error.missing": "Por favor complete su nombre y detalles sobre lo que desea forjar.",
    "custom.error.number": "WhatsApp no se encuentra configurado.",

    // Investment
    "invest.division": "División de Gestión de Patrimonios",
    "invest.title1": "El Estándar de la",
    "invest.title2": "Riqueza Intergeneracional",
    "invest.desc": "Oro físico de inversión 24K con estándar y calidad internacional LBMA. Almacenamiento seguro, custodia privada y logística blindada.",
    "invest.btn.start": "Iniciar Portafolio",
    "invest.btn.inventory": "Ver Catálogo",
    "invest.ticker.spot": "Precio Spot del Oro (XAU/USD):",
    "it.fore.tagline": "Proyección de Crecimiento",
    "it.fore.value": "+12.4% Est.",
    "it.fore.curve": "Rendimiento Anual Estimado",
    "it.calc.title": "Estimador de Costos",
    "it.calc.desc": "Calcule el presupuesto de adquisición de su lote de metal físico. Incluye gestiones, tasas de acuñación y certificación.",
    "it.calc.weight": "Seleccionar Peso (Gramos)",
    "it.calc.market": "Valor de Mercado",
    "it.calc.cert": "Certificación y Tasación",
    "it.calc.total": "Total Estimado",
    "it.calc.lock": "Congelar Cotización",
    "it.guar.tagline": "Garantías de AU718",
    "it.guar.title": "Protegiendo su Soberanía Financiera",
    "it.benefit1.title": "Ensayo de Pureza Dual",
    "it.benefit1.desc": "Análisis mediante tecnología de espectrometría XRF para asegurar una autenticidad absoluta.",
    "it.benefit2.title": "Logística Blindada",
    "it.benefit2.desc": "Ecoltas y camiones blindados de seguridad para entregas de gran volumen.",
    "it.benefit3.title": "Estructura Fiscal Eficiente",
    "it.benefit3.desc": "Asesoramiento para la tenencia optimizada de metales preciosos a nivel internacional.",
    "it.benefit4.title": "Garantía de Recompra",
    "it.benefit4.desc": "Compramos sus lingotes en el acto basándonos de manera transparente en las tasas diarias LBMA.",
    "it.catalog.title": "Catálogo de Metales",
    "it.catalog.tagline": "Pesos Estándar de Inversión",
    "it.catalog.inquire": "Consultar Disponibilidad",
    "it.faq.title": "Preguntas Frecuentes",
    "it.cta.tagline": "Estándares y Respaldos Internacionales",
    "it.cta.title": "¿Listo para diversificar en valor real?",
    "it.cta.btn": "Abrir cuenta corporativa",
    "it.cta.support": "Soporte VIP",

    // Shop
    "shop.tagline": "Exquisitez y Pureza",
    "shop.title": "Nuestra Colección",
    "shop.desc": "Piezas seleccionadas meticulosamente por sus acabados sobresalientes de elegancia atemporal. Vista el poder del oro puro.",
    "shop.collections": "Colecciones",
    "shop.purity": "Pureza (Quilates)",
    "shop.weight": "Peso",
    "shop.all_weights": "Todos los pesos",
    "shop.active_filters": "Filtros activos:",
    "shop.clear_all": "Limpiar todo",
    "shop.quick_view": "Vista rápida",
    "shop.order": "Pedir por WhatsApp",
    "shop.no_items": "No se encontraron piezas",
    "shop.no_items_desc": "La bóveda se está actualizando en este momento. Vuelva a intentar pronto o contáctenos de forma directa.",
    "shop.voices": "Clientes de Prestigio",
    "shop.clients": "Voces de Confianza",
    "shop.complete_look": "Complete su Vestuario",
    "shop.grade": "Grado",
    "shop.net_weight": "Peso Neto",
    "shop.ready_to_ship": "Listo para despacho",
    "shop.filter_trigger": "Filtrar",
    "shop.refine": "Refinar Búsqueda",
    "shop.apply_filters": "Aplicar Filtros"
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.shop": "المتجر",
    "nav.investment": "الاستثمار",
    "nav.custom": "حسب الطلب",
    "nav.consultation": "الاستشارات",
    "nav.locations": "الفروع",
    "nav.switch": "اللغة",
    
    "hero.tagline": "معيار الثراء",
    "hero.title1": "امتلك الذهب.",
    "hero.title2": "وتقلد القوة.",
    "hero.desc": "مجموعات منتقاة بعناية من أفخم مجوهرات الذهب عيار ١٨ و ٢١ و ٢٤ قيراط في العالم. من قطع الزينة العصرية يدويّة الصنع إلى سبائك الاستثمار ذات العوائد المجزية.",
    "hero.btn.jewelry": "تسوّق المجوهرات",
    "hero.btn.invest": "استثمر في الذهب",
    "hero.explore": "استكشف AU718",
    
    "feat.tagline": "عالمنا المنتقى",
    "feat.title": "مجموعاتنا المميّزة",
    "feat.view_all": "عرض جميع المجوهرات",
    "feat.view_col": "عرض المجموعة",
    
    "loc.tagline": "تواجدنا وحضورنا العالمي",
    "loc.title": "عناوين ومواقع الفروع",
    "loc.desc": "اختبر عظمة وجاذبية الذهب الخالص بنفسك. تفضل بزيارة صالات العرض الفاخرة لدينا للاطلاع الخاص والحصول على استشارات حصرية.",
    "loc.address_label": "العنوان",
    "loc.working_hours_title": "ساعات العمل",
    "loc.working_hours_details": "الاثنين - السبت: ٩:٠٠ صباحاً - ٦:٠٠ مساءً",
    "loc.direct_contact": "الاتصال المباشر",
    "loc.get_directions": "الحصول على الاتجاهات",
    "loc.cant_visit_title": "هل يتعذر عليك زيارة فروعنا؟",
    "loc.cant_visit_desc": "نوفر نقل وشحن آمن وسري تماماً لجميع أنحاء البلاد وخارجها. كافة الشحنات مؤمنة بالكامل من خزائننا حتى باب منزلك.",
    "loc.global_shipping": "شحن دولي عالمي",
    "loc.video_consults": "استشارات مرئية بالفيديو",
    "loc.lagos_shipping": "التوصيل داخل لاغوس",
    "loc.lagos_shipping_desc": "توصيل سريع في نفس اليوم أو من ١-٥ أيام عبر خدمة النقل الفاخرة الآمنة بضمان كامل.",
    "loc.nationwide_delivery": "التوصيل المحلي لكافة المدن",
    "loc.nationwide_delivery_desc": "خلال ٣-١٠ أيام عمل لأي مدينة رئيسية في نيجيريا مع إمكانية التتبع المباشر لخط سير الشحنة.",
    "loc.intl_shipping": "الشحن والتوصيل الدولي",
    "loc.intl_shipping_desc": "متاح وموفر بناءً على الطلب بالتنسيق مع كبرى شركات الشحن الدولي والخدمات الأمنية الخاصة.",
    "loc.modal.access": "دخول صالة العرض الحصرية",
    "loc.modal.showroom": "صالة العرض",
    "loc.modal.address_details": "تفاصيل العنوان",
    "loc.modal.copy_address": "نسخ العنوان كاملاً",
    "loc.modal.copied": "تم النسخ",
    "loc.modal.gmaps": "اتجاهات خرائط جوجل",
    "loc.modal.amaps": "خرائط آبل",
    "loc.active_gps": "إحداثيات الملاحة النشطة",
    "loc.city.Port Harcourt": "بورت هاركورت",
    "loc.address.Port Harcourt": "رقم ١٠ شارع واري، دي-لاين",
    "loc.city.Lagos": "لاغوس",
    "loc.address.Lagos": "سوق تيجوشو الحديث المتكامل، يابا",
    "loc.whatsapp_contact": "الاتصال عبر واتساب",
    
    "success.copied": "تم نسخ عنوان المعرض إلى الحافظة بنجاح!",
    "btn.add": "إضافة",

    // Footer
    "footer.newsletter.title": "وصول حصري وتحديثات",
    "footer.newsletter.desc": "لا تفوّت أبداً فرص إعادة التخزين أو إطلاق المجموعات الخاصة الحصرية. اشترك الآن.",
    "footer.newsletter.placeholder": "Excellence@gold.com",
    "footer.newsletter.button": "انضم إلى الدائرة الحصرية",
    "footer.brand_desc": "الوجهة الأولى والمميزة في نيجيريا للمجوهرات الفاخرة والاستثمار في الذهب والملاذ الآمن لقيم النقاوة.",
    "footer.quick_links": "روابط سريعة",
    "footer.inner_circle": "الدائرة الخاصة",
    "footer.visit_us": "تفضل بزيارتنا",
    "footer.link_shop": "مجموعة مجوهراتنا الراقية",
    "footer.link_invest": "سبائك الذهب الاستثمارية",
    "footer.link_custom": "خدمة التصميم الخاص والطلب",
    "footer.link_consult": "حجز جلسة استشارية خاصة",
    "footer.link_stores": "فروعنا ومعارضنا",
    "footer.order_whatsapp": "الطلب والتنسيق عبر واتساب",
    "footer.delivery_guaranteed": "شحن وتوصيل مؤمّن عالمياً • أصالة ونقاوة مضمونة بالكامل",
    "footer.validation_format": "يرجى إدخال عنوان بريد إلكتروني صحيح (مثال: name@domain.com)",
    "footer.processing_access": "جاري معالجة الطلب...",
    "footer.newsletter.btn_loading": "جاري معالجة الطلب...",
    "footer.newsletter.success": "مرحباً بك في الإرث العريق. تم تأمين عضويتك بنجاح.",
    "footer.newsletter.already": "أنت بالفعل جزء من دائرتنا النخبوية الخاصة.",
    "footer.newsletter.error": "حدث خطأ ما. يرجى التحقق من اتصال الشبكة وإعادة المحاولة.",
    "footer.newsletter.invalid": "يرجى كتابة عنوان بريد إلكتروني صالح.",
    "footer.services.title": "خدماتنا العريقة",
    "footer.services.shipping": "شحن مؤمن ومضمون بالكامل",
    "footer.services.secure": "حفظ وحيازة في خزائن خاصة",
    "footer.services.expert": "تقييم وتسعير احترافي للذهب",
    "footer.contact": "الكونسيرج المميّز",
    "footer.rights": "جميع الحقوق محفوظة. رمز الامتياز والتميز.",

    // Home
    "home.why.title1": "عيار ١٨ / ب٢١",
    "home.why.desc1": "مجموعات إيطالية فاخرة",
    "home.why.title2": "٠٪ رسوم",
    "home.why.desc2": "حفظ وحيازة الذهب الاستثماري",
    "home.why.title3": "دبي",
    "home.why.desc3": "بوليفارد الشيخ محمد بن راشد، وسط المدينة",
    "home.why.title4": "لاغوس",
    "home.why.desc4": "سوق تيجوشو، جزيرة فيكتوريا",
    "home.standard.tagline": "حفظ وحماية الثروات",
    "home.standard.title": "معيار عيار ٢٤ قيراط",
    "home.standard.desc": "الذهب ليس مجرد زينة، بل هو إرث عريق وثروة دائمة. استثمر في سبائك الذهب الخالص عيار ٢٤ قيراط بنسبة نقاء ٩٩.٩٪ لحماية مدخراتك من التضخم. نوفر الأمان المطلق لمستقبلك بكافة الأوزان من غرام واحد إلى كيلوغرام.",
    "home.standard.btn": "ابدأ الاستثمار الآن",
    "home.reviews.tagline": "آراء وتجارب العملاء",
    "home.reviews.title": "تجربة عملاء AU718",
    "home.cta.title": "هل أنت مستعد لامتلاك الامتياز؟",
    "home.cta.desc": "انضم إلى آلاف العملاء المستثمرين حول العالم الذين يثقون في AU718 لتلبية احتياجاتهم الراقية من الذهب.",
    "home.cta.whatsapp": "طلب فوري عبر واتساب",
    "home.cta.instagram": "تابعنا على إنستغرام",

    // Consultation
    "consult.tagline": "الكونسيرج الخاص",
    "consult.title": "الاستشارات الفردية المغلقة",
    "consult.desc": "عش تجربة مشاهدة خاصة ومغلقة في صالات العرض الراقية التابعة لنا أو احجز جلسة مرئية عن بُعد مع فريق المصممين المحترفين لدينا لتبدأ في صياغة إرثك الثمين.",
    "consult.prop1.title": "نقاء موثق بالكامل",
    "consult.prop1.desc": "تحقق من نقاء وجودة أصولك من الذهب عيار ١٨ إلى ٢٤ قيراط بإشراف خبرائنا المعتمدين.",
    "consult.prop2.title": "صالة العرض الخاصة",
    "consult.prop2.desc": "أجنحة خاصة راقية مجهزة في لاغوس وأبوجا للزيارات والمشاهدة الفعلية الخاصة.",
    "consult.hours.tagline": "متوفرون يومياً",
    "consult.hours.time": "من الساعة ٠٩:٠٠ صباحاً حتى ٠٦:٠٠ مساءً بتوقيت غرب أفريقيا",
    "consult.whatsapp.tagline": "واتساب المباشر",
    "consult.form.title": "طلب تصريح الوصول",
    "consult.form.name": "الاسم الكامل",
    "consult.form.name.placeholder": "على سبيل المثال: أليكو دانغوتي",
    "consult.form.contact": "بيانات الاتصال (البريد الإلكتروني أو الهاتف)",
    "consult.form.contact.placeholder": "يفضل رقم واتساب",
    "consult.form.service": "الخدمة المطلوبة",
    "consult.form.service.option1": "تصميم مجوهرات مخصصة ومصنعة خصيصاً لك",
    "consult.form.service.option2": "الاستثمار في سبائك الذهب (حضور شخصي)",
    "consult.form.service.option3": "فحص وتوثيق نقاء الأصول والمجوهرات",
    "consult.form.service.option4": "شراكات الجملة والوكلاء",
    "consult.form.date": "التاريخ المفضل",
    "consult.form.notes": "ملاحظات وتفاصيل إضافية",
    "consult.form.notes.placeholder": "حدد العيار المطلق، رؤيتك في التصميم، أو حجم الاستثمار المرغوب...",
    "consult.form.btn.loading": "جاري إرسال الطلب...",
    "consult.form.btn.schedule": "جدولة جلسة المشاهدة الخاصة",
    "consult.success": "تم تسجيل طلب الاستشارة الخاصة بنجاح. سيتواصل معكم الكونسيرج الخاص بنا في أقرب وقت لتنسيق الموعد.",
    "consult.error": "تم مقاطعة العملية بسبب خطأ في الشبكة. نرجو التواصل معنا مباشرة عبر واتساب.",

    // Custom
    "custom.tagline": "تخيل رؤيتك وسيصوغها محترفونا.",
    "custom.title": "صياغة وتصميم قطع المجوهرات الفريدة",
    "custom.desc": "تميز بقطع فريدة تعبر عن شخصيتك وتفردك وعزز أناقتك. من خواتم الخطوبة الفاخرة إلى عقود المناسبات الكبرى — نصيغ خيالك ذهباً خالصاً ونقاءً لا يزول.",
    "custom.step1.title": "الفكرة المبدئية",
    "custom.step1.desc": "أرسل فكرتك، صور مرجعية أو رسماً مبدئياً لفريق التصميم المحترف الخاص بنا.",
    "custom.step2.title": "نمذجة ثلاثية الأبعاد",
    "custom.step2.desc": "نوفر نموذجاً رقمياً عالي الدقة ومنظوراً ثلاثي الأبعاد لاعتماده والموافقة عليه قبل البدء في الصب والصياغة.",
    "custom.step3.title": "صياغة بأيدي خبراء وعلماء الذهب",
    "custom.step3.desc": "يقوم كبار الصاغة والمحترفين لدينا بصياغة وتصنيع قطعتك يدوياً بدقة فائقة باستخدام أجود المواد والنقاء العالي.",
    "custom.step4.title": "التدقيق ومراقبة الجودة",
    "custom.step4.desc": "تخضع كل قطعة لفحوصات واختبارات صارمة ودقيقة للنقاء لضمان اللمعان النهائي الخالي من أي عيوب.",
    "custom.form.title": "ابدأ مسيرتك الإبداعية معنا",
    "custom.form.name": "الاسم الكامل",
    "custom.form.name.placeholder": "أدخل اسمك الكامل هنا",
    "custom.form.type": "نوع المجوهرات المطلوبة",
    "custom.form.type.option1": "عقد / قلادة",
    "custom.form.type.option2": "خاتم",
    "custom.form.type.option3": "سوار",
    "custom.form.type.option4": "أقراط",
    "custom.form.type.option5": "تعليقة / تميمة مخصصة",
    "custom.form.karat": "العيار المرغوب",
    "custom.form.details": "تفاصيل ومواصفات المشروع",
    "custom.form.details.placeholder": "صف رؤيتك وتفاصيل الفكرة بالتفصيل — الأسلوب والنوع، الأحجار الكريمة، المقاس، المناسبة أو أي طلبات خاصة...",
    "custom.form.btn": "إرسال تفاصيل الصياغة عبر واتساب",
    "custom.quote": "\"لقد تمكنوا من تحويل رسم مبدئي بسيط رسمته بنفسي إلى إرث عائلي ثمين ستتوارثه ابنتي بكل كبرياء وأناقة لتتذكره للأبد.\"",
    "custom.quote.author": "— ميشيل أ.",
    "custom.error.missing": "يرجى تعبئة اسمك بالكامل وتفاصيل صياغة مشروعك المخصص قبل الإرسال.",
    "custom.error.number": "رقم واتساب المعتمد غير مهيأ بالكامل.",

    // Investment
    "invest.division": "إدارة وصيانة الثروات والأصول الثمينة",
    "invest.title1": "المعيار العالمي لحفظ و",
    "invest.title2": "توارث الثروة عبر الأجيال",
    "invest.desc": "سبائك الذهب الخالص عيار ٢٤ قيراط بنقاء معتمد وخاضع لمقاييس رابطة سوق لندن للمعادن الثمينة LBMA. خدمات تخزين آمنة بالكامل ولوجستيات حماية مسلحة للطلبات الكبرى.",
    "invest.btn.start": "تأسيس محفظة أصول الذهب",
    "invest.btn.inventory": "عرض المخزون المتاح",
    "invest.ticker.spot": "سعر الذهب الفوري بالدولار الأخرق (XAU/USD):",
    "it.fore.tagline": "توقعات النمو السنوي",
    "it.fore.value": "+١٢.٤٪ متوقع",
    "it.fore.curve": "منحنى العوائد والأرباح السنوية",
    "it.calc.title": "حاسبة التقدير الفوري للأصول",
    "it.calc.desc": "قدر رأس مالك الاستثماري المطلوب بدقة بناءً على أسعار السوق الحالية في الوقت الفعلي، وتكاليف شهادات التقييم والتوثيق.",
    "it.calc.weight": "اختر الوزن المطلوب بالغرام",
    "it.calc.market": "القيمة السوقية الفعلية للمعدن",
    "it.calc.cert": "صياغة وشهادات التوثيق والفحص",
    "it.calc.total": "الإجمالي التقديري التراكمي",
    "it.calc.lock": "تأمين وحفظ فارق السعر الفوري",
    "it.guar.tagline": "ضماناتنا العالمية",
    "it.guar.title": "ضمان وحماية سيادتك واستقرارك المالي",
    "it.benefit1.title": "فحص النقاوة المزدوج للأصول",
    "it.benefit1.desc": "تخضع كل سبيكة وقطعة لفحص مطياف الأشعة السينية المحوسب XRF إلى جانب اختبار الصهر التقليدي المعياري.",
    "it.benefit2.title": "لوجستيات وشحن مدرع آمن",
    "it.benefit2.desc": "توصيل وتسليم خاص تحت حماية مدرعة مسلحة لكافة كميات وطلبات المحافظ والشركات الكبرى والأوقاف.",
    "it.benefit3.title": "هيكلة ضريبية محسنة للأصول",
    "it.benefit3.desc": "استشارات حصرية لهيكلة حيازاتك من الذهب لتكون بأفضل كفاءة ضريبية ممكنة للمحافظ العائلية وصناديق التوارث.",
    "it.benefit4.title": "إعادة الشراء والمبادلة الفورية بمليار سيولة",
    "it.benefit4.desc": "مبادلة مخزونك القديم بسبائك حديثة معتمدة فوراً وبدون أي تأخير في تسييل السيولة وبناءً على أسعار السوق.",
    "it.catalog.title": "كتالوج السبائك ومخزن المعادن",
    "it.catalog.tagline": "أوزان الذهب الاستثمارية القياسية والسبائك",
    "it.catalog.inquire": "الاستعلام عن التوفر والطلب",
    "it.faq.title": "الأسئلة الشائعة حول الاستثمار وحفظ الثروات",
    "it.cta.tagline": "توثيقات بأعلى المعايير العالمية المعتمدة",
    "it.cta.title": "هل أنت مستعد لنقل استثماراتك إلى قيم النقاوة والصلابة المطلقة؟",
    "it.cta.btn": "فتح وإعداد حساب استثماري عائلي",
    "it.cta.support": "قنوات الدعم المباشرة ذات الأولوية VIP",

    // Shop
    "shop.tagline": "النقاء والكمال العالي",
    "shop.title": "مجموعتنا الكاملة ومخزن الذهب",
    "shop.desc": "تم اختيار وتصميم كل قطعة بمقاومة عالية للنقاء والحرفية العريقة لتكون إرثاً دائماً وجزءاً من رونق الشمس.",
    "shop.collections": "المجموعات والسلاسل",
    "shop.purity": "درجة النقاء (العيار والذهب)",
    "shop.weight": "الوزن الصافي",
    "shop.all_weights": "عرض كافة الأوزان المتاحة",
    "shop.active_filters": "عناصر التصفية المفعلة حالياً:",
    "shop.clear_all": "إلغاء كافة شروط التصفية",
    "shop.quick_view": "نظرة سريعة وتفاصيل",
    "shop.order": "طلب الشراء والتنسيق عبر واتساب",
    "shop.no_items": "عذراً، لم يتم العثور على قطع متطابقة",
    "shop.no_items_desc": "يتم الآن تحديث محتويات خزائن العرض الخاصة بنا بالذهب الحديث. تفضل بزيارتنا لاحقاً أو اتصل بنا مباشرة لأي طلب خاص.",
    "shop.voices": "آراء نخبة عملائنا الكرام",
    "shop.clients": "تجارب وقصص من يثقون في معيارنا",
    "shop.complete_look": "أكمل أناقتك بالكامل",
    "shop.grade": "العيار والنقاء",
    "shop.net_weight": "الوزن الصافي المعياري",
    "shop.ready_to_ship": "جاهز للشحن الفوري المؤمّن",
    "shop.filter_trigger": "التصفية والفرز والتبويب",
    "shop.refine": "تعديل عناصر البحث والتصفية للذهب",
    "shop.apply_filters": "تطبيق شروط التصفية المحددة"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('au718_lang');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('au718_lang', lang);
  };

  const isRtl = language === 'ar';

  useEffect(() => {
    // Update HTML dir and lang attributes for full accessibility and language engine correctness
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    
    // Add specific body styling adjustments for the layout flow
    if (isRtl) {
      document.body.classList.add('font-arabic');
    } else {
      document.body.classList.remove('font-arabic');
    }
  }, [language, isRtl]);

  const t = (key: string, defaultValue?: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
